### ISSUE TITLE
Cuadro comparativo de TIPOS DE TEXTO

### ISSUE THREAD

**Issue by Ariadnamonserrat10** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-Ariadnamonserrat10#1]
Hecho por: Ariadna Monserrat López Aparicio 1BS
[TIPOS DE TEXTO (Cuadro comparativo).pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-Ariadnamonserrat10/files/9613799/TIPOS.DE.TEXTO.Cuadro.comparativo.pdf)

**Comment by ErikCuevas03** [comment]
19, buen trabajo

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
